"""estado inicial do schema

Revision ID: 79320940f13e
Revises: 
Create Date: 2026-07-27 09:31:30.894709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79320940f13e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnpj_consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('segmento', sa.String(), nullable=False),
    sa.Column('situacao_cadastral', sa.String(), nullable=False),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('consultado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnpj_consultas_cnpj'), 'cnpj_consultas', ['cnpj'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('bubble_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bubble_user_id'), 'users', ['bubble_user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('segmento', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'cnpj', name='uq_lead_owner_cnpj')
    )
    op.create_index(op.f('ix_leads_cnpj'), 'leads', ['cnpj'], unique=False)
    op.create_table('leads_ocultos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'cnpj', name='uq_oculto_owner_cnpj')
    )
    op.create_index(op.f('ix_leads_ocultos_cnpj'), 'leads_ocultos', ['cnpj'], unique=False)
    op.create_table('registros_ligacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('nota', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_ligacao')
    op.drop_index(op.f('ix_leads_ocultos_cnpj'), table_name='leads_ocultos')
    op.drop_table('leads_ocultos')
    op.drop_index(op.f('ix_leads_cnpj'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_bubble_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cnpj_consultas_cnpj'), table_name='cnpj_consultas')
    op.drop_table('cnpj_consultas')
    # ### end Alembic commands ###
